# Local Develope Environment
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/finance
        username: sky
        password: 123456
        driver-class-name: org.postgresql.Driver
