server:
    port: 8080

logging:
    config: classpath:log4j2/log4j2.xml
    level:
        org:
            hibernate:
                sql: error

spring:
    application:
        name: finance_manager

    security:
        user:
            name: user
            password: 1234

    datasource:
        url: jdbc:postgresql://localhost:54321/finance
        username: sky
        password: 123456
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
        generate-ddl: false
    
    profiles:
        include: oauth