# Local Develope Environment
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/finance
        username: ${POSTGRESQL_USER}
        password: ${POSTGRESQL_PASSWORD}
        driver-class-name: org.postgresql.Driver
